/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.back.telas;
import java.sql.*;
import br.com.back.dal.ModuloConexao;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author DaviAugustoKleiserdo
 */
public class TelaCalculo extends javax.swing.JInternalFrame {
Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;
ArrayList<Float> media = new ArrayList<>();
DefaultListModel model1 = new DefaultListModel();

DefaultListModel model2 = new DefaultListModel();
  String str;
  ArrayList<String> nomes = new ArrayList<>();
    /**
     * Creates new form TelaCalculo
     */
    public TelaCalculo() {
     
        initComponents();
        conexao  = ModuloConexao.conector();
        
    }
    
    private void limpanomes(){
    model2.clear();
    jlResultados.updateUI();
    }
    
  
private void calcular(){
   
    String sql = "select * from tb_customer_account where vl_total > 560 and id_customer between 1500 and 2700 ORDER BY vl_total DESC";
    try {
        pst = conexao.prepareStatement(sql);
        rs = pst.executeQuery();
        ResultSet result = pst.getResultSet();
        Float contador;
        String name;
       
        
        model1.clear();
       
        while(result.next()){
        if(result.getFloat("vl_total")>560 && result.getFloat("id_customer")>= 1500 && result.getFloat("id_customer")<=2700){
           contador = result.getFloat("vl_total");
           media.add(contador);
          } 
        
        if(result.getFloat("vl_total")>560 && result.getFloat("id_customer")>= 1500 && result.getFloat("id_customer")<=2700){
           name = result.getString("nm_customer");
           nomes.add(name);
         } 
        }
       
          float S = 0;
           float resultado;   
      for(Float e : media){
          S = S + e;
      }
    
      float linhas = media.size();
      
      resultado = S/linhas;
      
      String conversor;
      conversor = Float.toString(resultado);
      
      txtMedia.setText("R$"+""+conversor);
      model2.addElement(nomes); 
      jlResultados.setModel(model2);
          
     
       
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
        
    }
        
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("mysql?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        columnStatsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM ColumnStats c");
        columnStatsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : columnStatsQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("dbcliente?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        tbCustomerAccountQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM TbCustomerAccount t");
        tbCustomerAccountList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbCustomerAccountQuery.getResultList();
        tbCustomerAccountQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM TbCustomerAccount t");
        tbCustomerAccountList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbCustomerAccountQuery1.getResultList();
        tbCustomerAccountQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM TbCustomerAccount t");
        tbCustomerAccountList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbCustomerAccountQuery2.getResultList();
        tbCustomerAccountQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM TbCustomerAccount t");
        tbCustomerAccountList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbCustomerAccountQuery3.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalcula = new javax.swing.JTable();
        btnCalcula = new javax.swing.JButton();
        txtMedia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlResultados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Calcular Média");
        setName("TelaCalculo"); // NOI18N
        setPreferredSize(new java.awt.Dimension(991, 595));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbCustomerAccountList3, tblCalcula);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCustomer}"));
        columnBinding.setColumnName("Id Customer");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nmCustomer}"));
        columnBinding.setColumnName("Nm Customer");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpfCnpj}"));
        columnBinding.setColumnName("Cpf Cnpj");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${isActive}"));
        columnBinding.setColumnName("Is Active");
        columnBinding.setColumnClass(Character.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlTotal}"));
        columnBinding.setColumnName("Vl Total");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblCalcula);

        btnCalcula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/back/icones/Financial_Calculation-64.png"))); // NOI18N
        btnCalcula.setToolTipText("Calcular Média");
        btnCalcula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });

        jLabel1.setText("Média Calculada");

        jScrollPane2.setViewportView(jlResultados);

        jLabel2.setText("Nomes de clientes na ordem decrescente a partir de seus Saldos:");

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/back/icones/data_delete-64.png"))); // NOI18N
        btnApagar.setToolTipText("Apagar Nomes");
        btnApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/back/icones/refresh.png"))); // NOI18N
        btnAtualizar.setToolTipText("Atualizar Indices");
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCalcula, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(231, 231, 231)
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApagar)
                            .addComponent(btnCalcula)
                            .addComponent(btnAtualizar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setBounds(0, 0, 991, 603);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        // TODO add your handling code here:
      calcular();
   
    }//GEN-LAST:event_btnCalculaActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        // TODO add your handling code here:
        limpanomes();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    dispose();
    TelaCalculo calcula = new TelaCalculo();
    calcula.setVisible(true);
    calcula.show(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    
   
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCalcula;
    private java.util.List<br.com.back.telas.ColumnStats> columnStatsList;
    private javax.persistence.Query columnStatsQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlResultados;
    private java.util.List<br.com.back.telas.TbCustomerAccount> tbCustomerAccountList;
    private java.util.List<br.com.back.telas.TbCustomerAccount> tbCustomerAccountList1;
    private java.util.List<br.com.back.telas.TbCustomerAccount> tbCustomerAccountList2;
    private java.util.List<br.com.back.telas.TbCustomerAccount> tbCustomerAccountList3;
    private javax.persistence.Query tbCustomerAccountQuery;
    private javax.persistence.Query tbCustomerAccountQuery1;
    private javax.persistence.Query tbCustomerAccountQuery2;
    private javax.persistence.Query tbCustomerAccountQuery3;
    private javax.swing.JTable tblCalcula;
    private javax.swing.JTextField txtMedia;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
