/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.back.telas;
import br.com.back.dal.ModuloConexao;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
/**
 *
 * @author DaviAugustoKleiserdo
 */
public class TelaCadastra extends javax.swing.JInternalFrame {
Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form TelaCadrastra
     */
    public TelaCadastra() {
        initComponents();
        conexao  = ModuloConexao.conector();
        cbxEstadoCliente.setSelectedItem(null);
        txtCodCliente.setDocument(new SoNumeros());
        txtCpf.setDocument(new SoNumeros());
        txtSaldo.setDocument(new digitarSaldo());
        txtNmCliente.setDocument(new SoLetras());
        
       
    }
private void adicionar(){
    String sql = "insert into tb_customer_account(id_customer,cpf_cnpj,nm_customer,is_active,vl_total) values(?,?,?,?,?)";
    
    try {
        
        pst = conexao.prepareStatement(sql);
        pst.setString(1,txtCodCliente.getText());
        pst.setString(2,txtCpf.getText());
        pst.setString(3,txtNmCliente.getText());
        pst.setString(4,cbxEstadoCliente.getSelectedItem().toString());
        pst.setString(5,txtSaldo.getText());
        if(txtCodCliente.getText().isEmpty() || txtNmCliente.getText().isEmpty() || txtCpf.getText().isEmpty() || txtSaldo.getText().isEmpty() || cbxEstadoCliente.getSelectedItem().equals(null) ){
           JOptionPane.showMessageDialog(null, "Preencher todos os campos!"); 
        }else{
       
        int adicionado = pst.executeUpdate();
        
        if(adicionado > 0){
            JOptionPane.showMessageDialog(null, "Cliente adicionado com sucesso!");
            txtCodCliente.setText(null);
            txtCpf.setText(null);
            txtNmCliente.setText(null);
            cbxEstadoCliente.setSelectedItem(null);
            txtSaldo.setText(null);
            
        
        }
        
        }
    } catch (Exception e) {
     
      JOptionPane.showMessageDialog(null, e+": "+"Erro ao cadastrar cliente!");
    
  }
}
  private void limpacampos(){
    txtCodCliente.setText(null);
    txtCpf.setText(null);
    txtNmCliente.setText(null);
    txtSaldo.setText(null);
    cbxEstadoCliente.setSelectedItem(null);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtNmCliente = new javax.swing.JTextField();
        txtCodCliente = new javax.swing.JTextField();
        btnCadastra = new javax.swing.JButton();
        cbxEstadoCliente = new javax.swing.JComboBox<>();
        btnDeleta = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(991, 595));
        setName("TelaCadastra"); // NOI18N
        setPreferredSize(new java.awt.Dimension(991, 595));

        jLabel1.setText("Código do Cliente");

        jLabel2.setText("Nome do Cliente");

        jLabel3.setText("CPF ou CNPJ");

        jLabel4.setText("Saldo do Cliente");

        jLabel5.setText("Cliente Ativo?");

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });

        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfKeyTyped(evt);
            }
        });

        txtNmCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNmClienteKeyTyped(evt);
            }
        });

        txtCodCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyTyped(evt);
            }
        });

        btnCadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/back/icones/Database-Add-64.png"))); // NOI18N
        btnCadastra.setToolTipText("Adicionar Cliente");
        btnCadastra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        cbxEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));

        btnDeleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/back/icones/data_delete-64.png"))); // NOI18N
        btnDeleta.setToolTipText("Apagar Campos");
        btnDeleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleta)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbxEstadoCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(135, 356, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastra)
                    .addComponent(btnDeleta))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setBounds(0, 0, 991, 595);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        // TODO add your handling code here:
        adicionar();
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletaActionPerformed
        // TODO add your handling code here:
        limpacampos();
    }//GEN-LAST:event_btnDeletaActionPerformed

    private void txtCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtCodClienteKeyPressed

    private void txtCodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyTyped
        // TODO add your handling code here:
        int numero=3;
        
        
            if(txtCodCliente.getText().length()>numero) {
            evt.consume();
    } else {
            
    }
    
    
    }//GEN-LAST:event_txtCodClienteKeyTyped

    private void txtNmClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNmClienteKeyTyped
        // TODO add your handling code here:
      int numero=30;
        if(txtNmCliente.getText().length()>numero) {
            evt.consume();
    } else {
            
    }
        
         
    }//GEN-LAST:event_txtNmClienteKeyTyped

    private void txtCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyTyped
        // TODO add your handling code here:
         int numero=8;
            if(txtCpf.getText().length()>numero) {
            evt.consume();
    } else {
            
    }
    }//GEN-LAST:event_txtCpfKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        // TODO add your handling code here:
         int numero=4;
            if(txtSaldo.getText().length()>numero) {
            evt.consume();
    } else {
            
    }
    }//GEN-LAST:event_txtSaldoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JComboBox<String> cbxEstadoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNmCliente;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
