/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.back.telas;

import br.com.back.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import br.com.back.dal.ModuloConexao;

/**
 *
 * @author DaviAugustoKleiserdo
 */
public class TelaPrincipal extends javax.swing.JFrame {
Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form AdicionaCliente
     */
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao  = ModuloConexao.conector();
       //System.out.println(conexao);
       
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        Sair = new javax.swing.JMenuBar();
        menCadastra = new javax.swing.JMenu();
        menNovoCliente = new javax.swing.JMenuItem();
        menCalc = new javax.swing.JMenu();
        menGera = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenu();
        menFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Desktop.setName("Desktop"); // NOI18N

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        menCadastra.setText("Cadastrar Cliente");
        menCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastraActionPerformed(evt);
            }
        });

        menNovoCliente.setText("Novo Cliente");
        menNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menNovoClienteActionPerformed(evt);
            }
        });
        menCadastra.add(menNovoCliente);

        Sair.add(menCadastra);

        menCalc.setText("Calcular Média");
        menCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCalcActionPerformed(evt);
            }
        });

        menGera.setText("Gerar Média");
        menGera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menGeraActionPerformed(evt);
            }
        });
        menCalc.add(menGera);

        Sair.add(menCalc);

        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });

        menFechar.setText("Fechar");
        menFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFecharActionPerformed(evt);
            }
        });
        menSair.add(menFechar);

        Sair.add(menSair);

        setJMenuBar(Sair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(991, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
     
    }//GEN-LAST:event_menSairActionPerformed

    private void menFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFecharActionPerformed
     int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION );
     if (sair == JOptionPane.YES_OPTION){
         System.exit(0);
     }
    }//GEN-LAST:event_menFecharActionPerformed

    private void menCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCalcActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menCalcActionPerformed

    private void menGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menGeraActionPerformed
       TelaCalculo calcula = new TelaCalculo();
       calcula.setVisible(true);
       Desktop.add(calcula);     
  
    }//GEN-LAST:event_menGeraActionPerformed

    private void menNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menNovoClienteActionPerformed
       TelaCadastra cadastra = new TelaCadastra();
       cadastra.setVisible(true);
       Desktop.add(cadastra);
    }//GEN-LAST:event_menNovoClienteActionPerformed

    private void menCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadastraActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){ 
this.dispose(); 
}
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Sair;
    private javax.swing.JMenu menCadastra;
    private javax.swing.JMenu menCalc;
    private javax.swing.JMenuItem menFechar;
    private javax.swing.JMenuItem menGera;
    private javax.swing.JMenuItem menNovoCliente;
    private javax.swing.JMenu menSair;
    // End of variables declaration//GEN-END:variables
}
